type Todo {
  id: ID!
  text: String!
  done: Boolean!
}

extend type Query {
  todos: [Todo!]!
}
input CreateTodoInput {
  text: String!
}
extend type Mutation {
  createTodo(input: CreateTodoInput!): Todo!
  updateTodoDone(id: ID!, done: Boolean!): Todo!
}

extend type Subscription {
  todoCreated: [Todo!]!
  todoUpdated: [Todo!]!
}